# Generated by Django 2.2.1 on 2019-12-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('hour', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'actividades',
            },
        ),
        migrations.CreateModel(
            name='Cosa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('actividad_id', models.ForeignKey(on_delete=models.SET(-1), to='example.Actividad')),
            ],
            options={
                'db_table': 'cosas',
            },
        ),
        migrations.DeleteModel(
            name='Example',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='inventory_id',
        ),
        migrations.DeleteModel(
            name='User2',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
